version: '2'

services:
  app:
    build: .
    command: ["php", "./index.php"]
    restart: always
    container_name: phpcont
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "18000:8000"
